// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.com.bim.pay.domain;

import au.com.bim.pay.domain.Customer;
import au.com.bim.pay.domain.CustomerDataOnDemand;
import au.com.bim.pay.domain.Job;
import au.com.bim.pay.domain.JobDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect JobDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JobDataOnDemand: @Component;
    
    private Random JobDataOnDemand.rnd = new SecureRandom();
    
    private List<Job> JobDataOnDemand.data;
    
    @Autowired
    CustomerDataOnDemand JobDataOnDemand.customerDataOnDemand;
    
    public Job JobDataOnDemand.getNewTransientJob(int index) {
        Job obj = new Job();
        setCustomer(obj, index);
        setDescription(obj, index);
        setEndDate(obj, index);
        setStartDate(obj, index);
        return obj;
    }
    
    public void JobDataOnDemand.setCustomer(Job obj, int index) {
        Customer customer = customerDataOnDemand.getRandomCustomer();
        obj.setCustomer(customer);
    }
    
    public void JobDataOnDemand.setDescription(Job obj, int index) {
        String description = "description_" + index;
        if (description.length() > 60) {
            description = description.substring(0, 60);
        }
        obj.setDescription(description);
    }
    
    public void JobDataOnDemand.setEndDate(Job obj, int index) {
        Date endDate = new Date(new Date().getTime() - 10000000L);
        obj.setEndDate(endDate);
    }
    
    public void JobDataOnDemand.setStartDate(Job obj, int index) {
        Date startDate = new Date(new Date().getTime() - 10000000L);
        obj.setStartDate(startDate);
    }
    
    public Job JobDataOnDemand.getSpecificJob(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Job obj = data.get(index);
        Long id = obj.getId();
        return Job.findJob(id);
    }
    
    public Job JobDataOnDemand.getRandomJob() {
        init();
        Job obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Job.findJob(id);
    }
    
    public boolean JobDataOnDemand.modifyJob(Job obj) {
        return false;
    }
    
    public void JobDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Job.findJobEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Job' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Job>();
        for (int i = 0; i < 10; i++) {
            Job obj = getNewTransientJob(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
