// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.com.bim.pay.domain;

import au.com.bim.pay.domain.WorkDone;
import au.com.bim.pay.domain.WorkDoneDataOnDemand;
import au.com.bim.pay.domain.WorkDoneIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkDoneIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkDoneIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkDoneIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WorkDoneIntegrationTest: @Transactional;
    
    @Autowired
    WorkDoneDataOnDemand WorkDoneIntegrationTest.dod;
    
    @Test
    public void WorkDoneIntegrationTest.testCountWorkDones() {
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to initialize correctly", dod.getRandomWorkDone());
        long count = WorkDone.countWorkDones();
        Assert.assertTrue("Counter for 'WorkDone' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkDoneIntegrationTest.testFindWorkDone() {
        WorkDone obj = dod.getRandomWorkDone();
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to provide an identifier", id);
        obj = WorkDone.findWorkDone(id);
        Assert.assertNotNull("Find method for 'WorkDone' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WorkDone' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkDoneIntegrationTest.testFindAllWorkDones() {
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to initialize correctly", dod.getRandomWorkDone());
        long count = WorkDone.countWorkDones();
        Assert.assertTrue("Too expensive to perform a find all test for 'WorkDone', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WorkDone> result = WorkDone.findAllWorkDones();
        Assert.assertNotNull("Find all method for 'WorkDone' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WorkDone' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkDoneIntegrationTest.testFindWorkDoneEntries() {
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to initialize correctly", dod.getRandomWorkDone());
        long count = WorkDone.countWorkDones();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WorkDone> result = WorkDone.findWorkDoneEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WorkDone' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WorkDone' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkDoneIntegrationTest.testFlush() {
        WorkDone obj = dod.getRandomWorkDone();
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to provide an identifier", id);
        obj = WorkDone.findWorkDone(id);
        Assert.assertNotNull("Find method for 'WorkDone' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWorkDone(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WorkDone' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkDoneIntegrationTest.testMergeUpdate() {
        WorkDone obj = dod.getRandomWorkDone();
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to provide an identifier", id);
        obj = WorkDone.findWorkDone(id);
        boolean modified =  dod.modifyWorkDone(obj);
        Integer currentVersion = obj.getVersion();
        WorkDone merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WorkDone' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkDoneIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to initialize correctly", dod.getRandomWorkDone());
        WorkDone obj = dod.getNewTransientWorkDone(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WorkDone' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'WorkDone' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WorkDoneIntegrationTest.testRemove() {
        WorkDone obj = dod.getRandomWorkDone();
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkDone' failed to provide an identifier", id);
        obj = WorkDone.findWorkDone(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'WorkDone' with identifier '" + id + "'", WorkDone.findWorkDone(id));
    }
    
}
