// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.com.bim.pay.domain;

import au.com.bim.pay.domain.WorkType;
import au.com.bim.pay.domain.WorkTypeDataOnDemand;
import au.com.bim.pay.domain.WorkTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WorkTypeIntegrationTest: @Transactional;
    
    @Autowired
    WorkTypeDataOnDemand WorkTypeIntegrationTest.dod;
    
    @Test
    public void WorkTypeIntegrationTest.testCountWorkTypes() {
        Assert.assertNotNull("Data on demand for 'WorkType' failed to initialize correctly", dod.getRandomWorkType());
        long count = WorkType.countWorkTypes();
        Assert.assertTrue("Counter for 'WorkType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkTypeIntegrationTest.testFindWorkType() {
        WorkType obj = dod.getRandomWorkType();
        Assert.assertNotNull("Data on demand for 'WorkType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkType' failed to provide an identifier", id);
        obj = WorkType.findWorkType(id);
        Assert.assertNotNull("Find method for 'WorkType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WorkType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkTypeIntegrationTest.testFindAllWorkTypes() {
        Assert.assertNotNull("Data on demand for 'WorkType' failed to initialize correctly", dod.getRandomWorkType());
        long count = WorkType.countWorkTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'WorkType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WorkType> result = WorkType.findAllWorkTypes();
        Assert.assertNotNull("Find all method for 'WorkType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WorkType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkTypeIntegrationTest.testFindWorkTypeEntries() {
        Assert.assertNotNull("Data on demand for 'WorkType' failed to initialize correctly", dod.getRandomWorkType());
        long count = WorkType.countWorkTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WorkType> result = WorkType.findWorkTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WorkType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WorkType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkTypeIntegrationTest.testFlush() {
        WorkType obj = dod.getRandomWorkType();
        Assert.assertNotNull("Data on demand for 'WorkType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkType' failed to provide an identifier", id);
        obj = WorkType.findWorkType(id);
        Assert.assertNotNull("Find method for 'WorkType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWorkType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WorkType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkTypeIntegrationTest.testMergeUpdate() {
        WorkType obj = dod.getRandomWorkType();
        Assert.assertNotNull("Data on demand for 'WorkType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkType' failed to provide an identifier", id);
        obj = WorkType.findWorkType(id);
        boolean modified =  dod.modifyWorkType(obj);
        Integer currentVersion = obj.getVersion();
        WorkType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WorkType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'WorkType' failed to initialize correctly", dod.getRandomWorkType());
        WorkType obj = dod.getNewTransientWorkType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WorkType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WorkType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'WorkType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WorkTypeIntegrationTest.testRemove() {
        WorkType obj = dod.getRandomWorkType();
        Assert.assertNotNull("Data on demand for 'WorkType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkType' failed to provide an identifier", id);
        obj = WorkType.findWorkType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'WorkType' with identifier '" + id + "'", WorkType.findWorkType(id));
    }
    
}
