// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.com.bim.pay.domain;

import au.com.bim.pay.domain.WorkType;
import au.com.bim.pay.domain.WorkTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect WorkTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WorkTypeDataOnDemand: @Component;
    
    private Random WorkTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<WorkType> WorkTypeDataOnDemand.data;
    
    public WorkType WorkTypeDataOnDemand.getNewTransientWorkType(int index) {
        WorkType obj = new WorkType();
        setDescription(obj, index);
        return obj;
    }
    
    public void WorkTypeDataOnDemand.setDescription(WorkType obj, int index) {
        String description = "description_" + index;
        if (description.length() > 60) {
            description = description.substring(0, 60);
        }
        obj.setDescription(description);
    }
    
    public WorkType WorkTypeDataOnDemand.getSpecificWorkType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WorkType obj = data.get(index);
        Long id = obj.getId();
        return WorkType.findWorkType(id);
    }
    
    public WorkType WorkTypeDataOnDemand.getRandomWorkType() {
        init();
        WorkType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WorkType.findWorkType(id);
    }
    
    public boolean WorkTypeDataOnDemand.modifyWorkType(WorkType obj) {
        return false;
    }
    
    public void WorkTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WorkType.findWorkTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WorkType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WorkType>();
        for (int i = 0; i < 10; i++) {
            WorkType obj = getNewTransientWorkType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
